# https://taskfile.dev

version: '3'

tasks:
  run:
    cmds:
      - go run main.go --port {{.PORT | default "9090"}}
  test-debug:
    cmds:
      - go tool ginkgo run -p -vv -r --randomize-all
  test:
    cmds:
      - go tool ginkgo run -p -r --randomize-all
